version: 1.0.{build}
image: Linux
# nuget: 如果包源和CI服务器是相同地址的话可以配置这个
#   account_feed: true
#   project_feed: true
install:
  - dotnet nuget add source https://ci.appveyor.com/nuget/jidanfan-6k0dhkdnjc2w   -n jidanfan -u %nuget_user% -p %nuget_pwd% --store-password-in-clear-text
before_build:
  - sh: dotnet restore --configfile NuGet.Config
build_script:
  - sh: dotnet publish
# notifications:
#   - provider: Email
#     to:
#       - '{{commitAuthorEmail}}'
#       - xy_feng@qq.com
#     subject: 'Build {{status}} ' # optional
#     message: '{{template_variable_1}}, {{template_variable_2}}' # optional
#     on_build_success: true
#     on_build_failure: false
#     on_build_status_changed: false
