version: 1.0.{build}
configuration: Release 
#environment:
#  nuget_user: xy_feng@qq.com
#  nuget_password: 1
#install:
#- ps: >-
#    dotnet nuget  remove source jidanfan


#    dotnet nuget add source https://ci.appveyor.com/nuget/jidanfan-6k0dhkdnjc2w   -n jidanfan -u %nuget_user% -p %nuget_password% --store-password-in-clear-text
build:
  project: WebApplication1.sln
  verbosity: minimal

test_script:
- ps: dotnet test "XUnitTestProject1/XUnitTestProject1.csproj" --configuration Release--no-build

deploy_script:
- ps: >-
    Write-Host  "$env:APPVEYOR_REPO_TAG_NAME"

    Write-Host  "${env:APPVEYOR_REPO_TAG_NAME}"

    if ($env:APPVEYOR_REPO_TAG_NAME)
    {
      docker ps
    }
    else
    {
      docker images 
    }
#deploy:
#  - provider: Local 
#    on:
#      APPVEYOR_REPO_TAG: true
#    ps: ./deploy.ps1