version: 1.0.{build} 
configuration: Release 
#environment:
  #APPVEYOR_REPO_TAG: true
#  nuget_user: xy_feng@qq.com
#  nuget_password: 1
branches:
  only:
    - master
    - develop
install:
- ps: ./deploy.ps1 
#- ps: >-
#    dotnet nuget  remove source jidanfan

#skip_tags: true

    

#    dotnet nuget add source https://ci.appveyor.com/nuget/jidanfan-6k0dhkdnjc2w   -n jidanfan -u %nuget_user% -p %nuget_password% --store-password-in-clear-text
#build:
#  project: WebApplication1.sln
#  verbosity: minimal

#test_script:
#- ps: dotnet test "XUnitTestProject1/XUnitTestProject1.csproj" --configuration Release--no-build

#artifacts:
#  - path: dist/*.*    
#    name: myartifacts

#deploy:
#- provider: Local
#  artifact: myartifacts
#  on:
#    branch: master
#    APPVEYOR_REPO_TAG: true
#  ps: ./deploy.ps1

deploy_script:
- ps: >-
    "Hello world"

    "APPVEYOR_REPO_TAG: $Env:APPVEYOR_REPO_TAG"

    "appveyor_repo_tag: $Env:appveyor_repo_tag"

    "INFO: tag name: $Env:APPVEYOR_REPO_TAG_NAME"

    "INFO: $APPVEYOR_REPO_TAG_NAME"

    "APPVEYOR_REPO_TAG_NAME: $env:APPVEYOR_REPO_TAG_NAME"
   